package ch.nexusnet.chatmanager.chat;

import ch.nexusnet.chatmanager.chat.util.MessageListConverter;
import ch.nexusnet.chatmanager.message.Message;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;

@Getter
@Setter
@DynamoDBTable(tableName = "Chats")
public class Chat {

    private String participant1;
    private String participant2;
    private List<Message> messages = new ArrayList<>();

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return generateCompositeId(participant1, participant2);
    }

    public void setId(String id) {
        // This is needed otherwise DynamoDB will throw an exception
    }

    @DynamoDBAttribute(attributeName = "participant1")
    public String getParticipant1() {
        return participant1;
    }

    @DynamoDBAttribute(attributeName = "participant2")
    public String getParticipant2() {
        return participant2;
    }

    @DynamoDBAttribute(attributeName = "messages")
    @DynamoDBTypeConverted(converter = MessageListConverter.class)
    public List<Message> getMessages() {
        return messages;
    }

    public void addMessage(Message message) {
        messages.add(message);
    }

    private String generateCompositeId(String participant1, String participant2) {
        return participant1.compareTo(participant2) < 0 ?
                participant1 + ":" + participant2 : participant2 + ":" + participant1;
    }
}
