package ch.nexusnet.postmanager.aws.dynamodb.model.table;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@DynamoDBTable(tableName = "Posts")
public class DynamoDBLike {


    @DynamoDBHashKey(attributeName = "id")
    private String id;

    @DynamoDBAttribute(attributeName = "targetType")
    private String targetType;

    @DynamoDBAttribute(attributeName = "targetId")
    private String targetId;

    @DynamoDBAttribute(attributeName = "userId")
    private String userId;

    @DynamoDBAttribute(attributeName = "timestamp")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private String timestamp;

}
