package ch.nexusnet.postmanager.aws.dynamodb.model.table;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;

@Setter
@Getter
@DynamoDBTable(tableName = "Posts")
public class DynamoDBPost {

    @DynamoDBHashKey(attributeName = "id")
    private String id;

    @DynamoDBAttribute(attributeName = "authorId")
    private String authorId;

    @DynamoDBAttribute(attributeName = "type")
    private String type;

    @DynamoDBAttribute(attributeName = "status")
    private String status;

    @DynamoDBAttribute(attributeName = "title")
    private String title;

    @DynamoDBAttribute(attributeName = "image")
    private String image;

    @DynamoDBAttribute(attributeName = "shortDescription")
    private String shortDescription;

    @DynamoDBAttribute(attributeName = "description")
    private String description;

    @DynamoDBAttribute(attributeName = "likeNumber")
    private int likeNumber = 0;

    @DynamoDBAttribute(attributeName = "commentNumber")
    private int commentNumber = 0;

    @DynamoDBAttribute(attributeName = "hashtags")
    private List<String> hashtags = new ArrayList<>();

    @DynamoDBAttribute(attributeName = "createdDateTime")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private String createdDateTime;

    @DynamoDBAttribute(attributeName = "edited")
    private boolean edited;

    @DynamoDBAttribute(attributeName = "editedDateTime")
    private String editedDateTime;

    @DynamoDBAttribute(attributeName = "fileUrls")
    private List<String> fileUrls = new ArrayList<>();

    public void addFileUrl(String fileUrl) {
        fileUrl = fileUrl.replace("//", "/");
        fileUrls.add(fileUrl);
    }

    public void removeFileUrl(String fileUrl) {
        fileUrls.remove(fileUrl);
    }
}
