package ch.nexusnet.postmanager.aws.dynamodb.model.table;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
@DynamoDBTable(tableName = "Posts")
public class DynamoDBComment {

    @DynamoDBHashKey(attributeName = "id")
    private String id;

    @DynamoDBAttribute(attributeName = "postId")
    private String postId;

    @DynamoDBAttribute(attributeName = "authorId")
    private String authorId;

    @DynamoDBAttribute(attributeName = "content")
    private String content;

    @DynamoDBAttribute(attributeName = "createdDateTime")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private String createdDateTime;

    @DynamoDBAttribute(attributeName = "likeNumber")
    private int likeNumber = 0;
}
